Fixing "AttributeError: 'RcutilsLogger' object has no attribute 'warn'" (#521)
Signed-off-by: Christian Henkel <christian.henkel2@de.bosch.com>
(cherry picked from commit 048cd475045e69317309fcecd1d09f7f4e71ea47)